direction: right

entrée: {
  neurone1
  neurone2
  neurone3
  neurone4
}

cachée: {
  neurone5
  neurone6
  neurone7
  neurone8
  neurone9
}

sortie: {
  neurone10
}

entrée.neurone1 -> cachée.neurone5
entrée.neurone1 -> cachée.neurone6
entrée.neurone1 -> cachée.neurone7
entrée.neurone1 -> cachée.neurone8
entrée.neurone1 -> cachée.neurone9

entrée.neurone2 -> cachée.neurone5
entrée.neurone2 -> cachée.neurone6
entrée.neurone2 -> cachée.neurone7
entrée.neurone2 -> cachée.neurone8
entrée.neurone2 -> cachée.neurone9

entrée.neurone3 -> cachée.neurone5
entrée.neurone3 -> cachée.neurone6
entrée.neurone3 -> cachée.neurone7
entrée.neurone3 -> cachée.neurone8
entrée.neurone3 -> cachée.neurone9

entrée.neurone4 -> cachée.neurone5
entrée.neurone4 -> cachée.neurone6
entrée.neurone4 -> cachée.neurone7
entrée.neurone4 -> cachée.neurone8
entrée.neurone4 -> cachée.neurone9

cachée.neurone5 -> sortie.neurone10
cachée.neurone6 -> sortie.neurone10
cachée.neurone7 -> sortie.neurone10
cachée.neurone8 -> sortie.neurone10
cachée.neurone9 -> sortie.neurone10