graph width: 800px

  input_layer: [ "Neuron 1", "Neuron 2", "Neuron 3" ]
  hidden_layer: [ "Neuron 4", "Neuron 5", "Neuron 6" ]
  output_layer: [ "Neuron 7" ]

  input_layer -> hidden_layer
  hidden_layer -> output_layer